### ISSUE TITLE
Support for expanding URI templates

### ISSUE THREAD

**Issue by peritus** [wharris/dougrain#6]
`_links` often contain URI templates[http://tools.ietf.org/html/rfc6570], 

This is what I do at the moment:

```
the_url = uritemplate.expand( mydoc.links['myrel'].url(), { "a": b, "c": d, })
```

I'd like to have this functionality built into dougrain, so I can write

```
the_url = mydoc.links['myrel'].url(a=b, c=d)
```

Also, I'd have to re-read the HAL spec to figure out if there are situations where the values can be extrapolated from the document itself, so the url could expand automatically.

https://pypi.python.org/pypi/uritemplate is a great URI template library I've worked with.

**Comment by wharris** [comment]
dougrain already does this. For example, the following code prints `http://localhost/thing/t/template?c=expansion`:

``` python
import dougrain

mydoc = dougrain.Document.from_object(
    {'_links': {'self': {'href': "/"},
                'myrel': {'href': "/thing/{a:1}/{a}{?c}",
                          'templated': True}}},
    base_uri="http://localhost/")

b, d = "template expansion".split()

the_url = mydoc.links['myrel'].url(a=b, c=d)
print(the_url)
```

Note that the link must have its `"templated"` property set to `true`.

**Comment by peritus** [comment]
Nice! Thank you!
